import { useEffect, useRef, useState } from 'react';
import axios from 'axios';
import socket from '../socket';
import { getStoredPrivateKeyJwk, encryptMessage, decryptMessage } from '../utils/crypto';
import { decryptGroupKeyPackage, encryptGroupKeyForMember, generateGroupKey, getStoredGroupKey, storeGroupKey } from '../utils/groupCrypto';

export default function GroupChat({ group: initialGroup, token, userId }) {
  const [group,setGroup]=useState(initialGroup),[messages,setMessages]=useState([]),[key,setKey]=useState(null),[input,setInput]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const bottomRef=useRef(null), myId=userId?.toString();
  const load=async()=>{try{setLoading(true);const g=(await axios.get(`/api/groups/${initialGroup._id}`,{headers:{Authorization:`Bearer ${token}`}})).data;setGroup(g);let k=await getStoredGroupKey(g._id,g.keyVersion);if(!k){const p=g.keyPackage;if(!p)throw new Error('Paquet de clé du groupe indisponible.');const sender=g.members.find(m=>m._id?.toString()===p.senderId?.toString());if(!sender?.publicKey)throw new Error('Clé publique du distributeur indisponible.');const priv=getStoredPrivateKeyJwk(myId);if(!priv)throw new Error('Clé privée locale introuvable.');k=await decryptGroupKeyPackage(p.encryptedKey,priv,typeof sender.publicKey==='string'?JSON.parse(sender.publicKey):sender.publicKey);if(!k)throw new Error('Impossible de déchiffrer la clé du groupe.');await storeGroupKey(g._id,g.keyVersion,k);}setKey(k);const raw=(await axios.get(`/api/groups/${g._id}/messages`,{headers:{Authorization:`Bearer ${token}`}})).data;setMessages(await Promise.all(raw.map(async m=>{if(m.deleted)return m;const text=await decryptMessage(k,m.content);return text===null?{...m,content:null,decryptionError:true}:{...m,content:text,decryptionError:false};})));await axios.patch(`/api/groups/${g._id}/read`,{},{headers:{Authorization:`Bearer ${token}`}}).catch(()=>{});setError('');}catch(e){console.error(e);setError(e.response?.data?.error||e.message||'Impossible de charger le groupe.');}finally{setLoading(false);}};
  useEffect(()=>{load();},[initialGroup?._id,token,myId]);
  useEffect(()=>{const onMsg=async m=>{if(m.group?.toString()!==initialGroup._id.toString()||!key)return;const text=await decryptMessage(key,m.content);const d=text===null?{...m,content:null,decryptionError:true}:{...m,content:text,decryptionError:false};setMessages(p=>p.some(x=>x._id?.toString()===m._id?.toString())?p:[...p,d]);if(m.sender?.toString()!==myId)axios.patch(`/api/groups/${initialGroup._id}/read`,{},{headers:{Authorization:`Bearer ${token}`}}).catch(()=>{});};const refresh=({groupId})=>{if(groupId?.toString()===initialGroup._id.toString())load();};const del=({groupId,messageId})=>{if(groupId?.toString()===initialGroup._id.toString())setMessages(p=>p.filter(m=>m._id?.toString()!==messageId?.toString()));};socket.on('newGroupMessage',onMsg);socket.on('groupMessageSent',onMsg);socket.on('groupUpdated',refresh);socket.on('groupDeleted',refresh);socket.on('groupMessageDeleted',del);return()=>{socket.off('newGroupMessage',onMsg);socket.off('groupMessageSent',onMsg);socket.off('groupUpdated',refresh);socket.off('groupDeleted',refresh);socket.off('groupMessageDeleted',del);};},[initialGroup?._id,key,myId,token]);
  useEffect(()=>bottomRef.current?.scrollIntoView({behavior:'smooth'}),[messages]);
  const send=async()=>{const text=input.trim();if(!text||!key)return;try{socket.emit('sendGroupMessage',{groupId:group._id,content:await encryptMessage(key,text)});setInput('');}catch{setError('Impossible de chiffrer le message.');}};
  const leave=async()=>{if(!group)return;if(group.owner?.toString()===myId){if(!window.confirm('Supprimer définitivement ce groupe ?'))return;await axios.delete(`/api/groups/${group._id}`,{headers:{Authorization:`Bearer ${token}`}});return;}try{const priv=getStoredPrivateKeyJwk(myId),next=await generateGroupKey(),remaining=group.members.filter(m=>m._id?.toString()!==myId),packages=[];if(!priv)throw new Error('Clé privée locale introuvable.');for(const m of remaining){if(!m.publicKey)throw new Error('Clé publique d’un membre indisponible.');packages.push({userId:m._id.toString(),senderId:myId,version:group.keyVersion+1,encryptedKey:await encryptGroupKeyForMember(next,priv,typeof m.publicKey==='string'?JSON.parse(m.publicKey):m.publicKey)});}await axios.post(`/api/groups/${group._id}/leave`,{keyPackages:packages},{headers:{Authorization:`Bearer ${token}`}});localStorage.removeItem(`propard_groupkey_${group._id}_v${group.keyVersion}`);}catch(e){setError(e.response?.data?.error||e.message||'Impossible de quitter le groupe.');}};
  if(!group)return null;return <div style={s.container}><div style={s.header}><div style={s.avatar}>{(group.name||'?')[0].toUpperCase()}</div><div><p style={s.name}>{group.name}</p><p style={s.sub}>{group.memberCount||group.members?.length||0} membre(s)</p></div><button onClick={leave} style={s.leave}>{group.owner?.toString()===myId?'🗑️':'🚪'}</button></div><div style={s.messages}>{loading&&<p style={s.info}>Chargement...</p>}{!loading&&error&&<p style={{...s.info,color:'var(--danger)'}}>{error}</p>}{!loading&&!error&&messages.map(m=>{const sender=m.sender||{},sid=sender._id?.toString()||m.sender?.toString(),me=sid===myId;return <div key={m._id} style={{...s.row,justifyContent:me?'flex-end':'flex-start'}}><div style={{...s.bubble,background:me?'var(--accent)':'var(--bg-tertiary)',color:me?'#fff':'var(--text-primary)'}}>{!me&&<div style={s.sender}>{sender.displayName||sender.username||'Membre'}</div>}{m.decryptionError?'🔒 Message impossible à déchiffrer':m.content}</div></div>})}<div ref={bottomRef}/></div><div style={s.inputRow}><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Écrire un message..." style={s.input} disabled={!key}/><button onClick={send} style={s.send} disabled={!key||!input.trim()}>➤</button></div></div>;
}
const s={container:{flex:1,minHeight:0,display:'flex',flexDirection:'column',background:'var(--bg-primary)'},header:{display:'flex',alignItems:'center',gap:10,padding:'12px 16px',background:'var(--bg-secondary)',borderBottom:'1px solid var(--border)'},avatar:{width:38,height:38,borderRadius:'50%',background:'var(--accent-glow)',color:'var(--accent)',border:'1px solid var(--accent)',display:'grid',placeItems:'center',fontWeight:800},name:{margin:0,color:'var(--text-primary)',fontWeight:700},sub:{margin:0,color:'var(--text-muted)',fontSize:11},leave:{marginLeft:'auto',background:'transparent',border:'1px solid var(--border)',color:'var(--text-primary)',borderRadius:8,padding:'7px 10px'},messages:{flex:1,minHeight:0,overflowY:'auto',padding:16},info:{textAlign:'center',color:'var(--text-secondary)'},row:{display:'flex',marginBottom:8},bubble:{maxWidth:'75%',padding:'9px 12px',borderRadius:12,whiteSpace:'pre-wrap',overflowWrap:'anywhere'},sender:{fontSize:11,fontWeight:700,marginBottom:3,opacity:.8},inputRow:{display:'flex',gap:8,padding:12,borderTop:'1px solid var(--border)',background:'var(--bg-secondary)'},input:{flex:1,minWidth:0,background:'var(--bg-tertiary)',color:'var(--text-primary)',border:'1px solid var(--border)',borderRadius:9,padding:'10px 12px',outline:'none'},send:{width:42,border:0,borderRadius:9,background:'var(--accent)',color:'#fff',fontWeight:800}};
